name: "CI/CD NPM"

on: 
  push:
    branches: [main]
jobs:
    publish:
        runs-on: ubuntu-latest
        env:
          main_source_path: "./"
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: node
              uses: actions/setup-node@v3.8.1
              with:
                  clean: true
                  node-version: 20
                  registry-url: https://registry.npmjs.org
            - name : "configuring git"
              run: |
                git config --global user.email "${{github.actor}}@users.noreply.github.com"
                git config --global user.name "${{github.actor}}"
            - name : "install_dependencies"
              run: npm install
              working-directory: ${{env.main_source_path}}
            - name : "check build"
              run: npm pack --dry-run
              working-directory: ${{env.main_source_path}}
            - name : "versioning"
              run: |
                # based on repo
                # repository="${{github.repository}}"                
                # IFS='/' read -ra parts <<< "${repository}"
                # latest_version=$(npm view "${parts[1]}" version) 
                package_name=$(node -e "console.log(require('./package.json').name)")
                latest_version=$(npm view "${package_name}" version) 
                echo "$package_name"
                echo "$latest_version"
                npm version "$latest_version" --no-git-tag-version
                npm version patch --no-git-tag-version
              working-directory: ${{env.main_source_path}}
            - name : "build"
              run: npm run build
              working-directory: ${{env.main_source_path}}
            - name : "publish" 
              run: npm publish --access public
              working-directory: ${{env.main_source_path}}
              env:
                  NODE_AUTH_TOKEN: ${{secrets.LEARN_HUNGER}}